/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab2Ordinaite;

import java.io.File;
import javax.swing.JFileChooser;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.*;
import java.io.*;
import java.util.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import studijosKTU.ListKTUx;

/**
 *
 * @author rordi
 */
public class KnygaGVS extends javax.swing.JFrame {
    
    private KnygaBandymai knygaBan = new KnygaBandymai();
    private KnygaAtranka atrinkti = new KnygaAtranka();
    

    /**
     * Creates new form KnygaGVS
     */
    public KnygaGVS() {
        initComponents();
        MRikiavimas.setEnabled(false);
        MAtrinkimas.setEnabled(false);
        bVykdyti.setEnabled(false);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        tekstoLaukas = new javax.swing.JTextArea();
        lNuo = new javax.swing.JLabel();
        lIki = new javax.swing.JLabel();
        textNuo = new javax.swing.JTextField();
        textIki = new javax.swing.JTextField();
        bVykdyti = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MFailas = new javax.swing.JMenu();
        mIvesti = new javax.swing.JMenuItem();
        miLentele = new javax.swing.JMenuItem();
        miUzdaryti = new javax.swing.JMenuItem();
        MRikiavimas = new javax.swing.JMenu();
        miPavadinimas = new javax.swing.JMenuItem();
        miKaina = new javax.swing.JMenuItem();
        MAtrinkimas = new javax.swing.JMenu();
        miRibos = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tekstoLaukas.setColumns(20);
        tekstoLaukas.setRows(5);
        jScrollPane1.setViewportView(tekstoLaukas);

        lNuo.setText("Nuo");

        lIki.setText("Iki");

        textNuo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNuoActionPerformed(evt);
            }
        });

        bVykdyti.setText("Atrinkti");
        bVykdyti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVykdytiActionPerformed(evt);
            }
        });

        MFailas.setText("Failas");

        mIvesti.setText("Įvesti");
        mIvesti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIvestiActionPerformed(evt);
            }
        });
        MFailas.add(mIvesti);

        miLentele.setText("Spausdinti lentelę");
        miLentele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLenteleActionPerformed(evt);
            }
        });
        MFailas.add(miLentele);

        miUzdaryti.setText("Uždaryti");
        miUzdaryti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUzdarytiActionPerformed(evt);
            }
        });
        MFailas.add(miUzdaryti);

        jMenuBar1.add(MFailas);

        MRikiavimas.setText("Rikiavimas");

        miPavadinimas.setText("Pagal pavadinimą");
        miPavadinimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPavadinimasActionPerformed(evt);
            }
        });
        MRikiavimas.add(miPavadinimas);

        miKaina.setText("Pagal kainą");
        miKaina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miKainaActionPerformed(evt);
            }
        });
        MRikiavimas.add(miKaina);

        jMenuBar1.add(MRikiavimas);

        MAtrinkimas.setText("Atrinkimas");

        miRibos.setText("Pagal psl. skaičių");
        miRibos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRibosActionPerformed(evt);
            }
        });
        MAtrinkimas.add(miRibos);

        jMenuBar1.add(MAtrinkimas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lIki)
                    .addComponent(lNuo)
                    .addComponent(bVykdyti)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(textNuo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                        .addComponent(textIki, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lNuo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textNuo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lIki)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textIki, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(bVykdyti)
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void mIvestiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIvestiActionPerformed

       JFileChooser FC = new JFileChooser(".");
       FileNameExtensionFilter filtras = new FileNameExtensionFilter("TEXT FILES", "txt", "text");
       FC.setFileFilter(filtras);
       
       FC.setDialogTitle("Pasirinkite norimą failą");
       FC.setApproveButtonText("Atidaryti failą");
       int rez = FC.showOpenDialog(null); 
       
        if(rez == JFileChooser.APPROVE_OPTION)
        {
            
            File f1 = FC.getSelectedFile();
            knygaBan.loadAndPrint(f1, tekstoLaukas);
            mIvesti.setEnabled(false);
             if(knygaBan.knygos.size()>0)
             {
                 MRikiavimas.setEnabled(true);
                 MAtrinkimas.setEnabled(true);
             }

        }
             else if (rez == JFileChooser.ERROR_OPTION)
                {
			JOptionPane.showMessageDialog(null,
			"Klaida pasirinktame faile",
			"Skaitymas - rašymas", JOptionPane.ERROR_MESSAGE);
		}
              else if (rez == JFileChooser.CANCEL_OPTION)
                {
			JOptionPane.showMessageDialog(null, 
			"Skaitymo atsisakyta (paspaustas ESC arba Cancel)",
			"Skaitymas - rašymas", JOptionPane.WARNING_MESSAGE);
		}

    }//GEN-LAST:event_mIvestiActionPerformed

    private void miUzdarytiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUzdarytiActionPerformed

		System.exit(0);
    }//GEN-LAST:event_miUzdarytiActionPerformed

    private void miPavadinimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPavadinimasActionPerformed
         
         tekstoLaukas.append("\nRikiavimas pagal pavadinimą abėcėliškai:\n");
         knygaBan.knygos.sortBuble(Knyga.pagalPavadinima);
         tekstoLaukas.append(knygaBan.toString());
         
        
    }//GEN-LAST:event_miPavadinimasActionPerformed

    private void miKainaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miKainaActionPerformed
        
         tekstoLaukas.append("\nRikiavimas pagal kainą didėjimo tvarka:\n");
         knygaBan.knygos.sortBuble(Knyga.pagalKainą);
         tekstoLaukas.append(knygaBan.toString());
    }//GEN-LAST:event_miKainaActionPerformed

    private void miRibosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRibosActionPerformed
        
        JOptionPane.showMessageDialog(null, "Įveskite puslapių skaičių "
                + "lango kampe esančiuose \nlangeliuose ir spustelėkite mygtuką "
                + "atrinkti");
         bVykdyti.setEnabled(true);

    }//GEN-LAST:event_miRibosActionPerformed

    private void textNuoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNuoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNuoActionPerformed

    private void bVykdytiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVykdytiActionPerformed
        
        String nuoTekstas = textNuo.getText();
        String ikiTekstas = textIki.getText();
        int nuo = Integer.parseInt(nuoTekstas);
        int iki = Integer.parseInt(ikiTekstas);

        tekstoLaukas.append("\nAtrinkimas pagal kainą:\n");
        atrinkti.visos = knygaBan.knygos;
        knygaBan.knygos = atrinkti.atrinktiPagalPsl(nuo, iki);
        if(knygaBan.knygos.size() > 0)
        {
            tekstoLaukas.append(knygaBan.toString());
        }
        else
        {
            tekstoLaukas.append("Knygų, kurių kaina būtų tokiose ribose, nėra");
        }
         bVykdyti.setEnabled(false);
    }//GEN-LAST:event_bVykdytiActionPerformed

    private void miLenteleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLenteleActionPerformed
        JFrame fr = new JFrame();
            JPanel panel = new JPanel();
            panel.setLayout(new BorderLayout());
        
            JTable lentele = new JTable();
            String stulpeliai[] = {"Pavadinimas", "Autorius", "Žanras", 
            "Išleidimo metai", "Puslapių sk.", "Kaina" };
            DefaultTableModel lentelesMod = (DefaultTableModel) lentele.getModel();
            JScrollPane valdymas = new JScrollPane(lentele);
            panel.add(new JLabel("Duomenys", SwingConstants.CENTER), BorderLayout.WEST);
            panel.add(valdymas, BorderLayout.CENTER);
            lentelesMod.setColumnIdentifiers(stulpeliai);
            
            for(Knyga k: knygaBan.knygos)
            {
                lentelesMod.addRow(new Object[] {k.ImtiPavadinima(),
                    k.ImtiAutoriu(), k.ImtiZanra(), k.ImtiMetus(), 
                    k.ImtiPuslapius(), k.ImtiKaina()});
 
            }
             fr.add(panel);
             fr.setSize(600, 200);
             fr.setVisible(true);
    }//GEN-LAST:event_miLenteleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KnygaGVS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KnygaGVS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KnygaGVS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KnygaGVS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KnygaGVS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MAtrinkimas;
    private javax.swing.JMenu MFailas;
    private javax.swing.JMenu MRikiavimas;
    private javax.swing.JButton bVykdyti;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lIki;
    private javax.swing.JLabel lNuo;
    private javax.swing.JMenuItem mIvesti;
    private javax.swing.JMenuItem miKaina;
    private javax.swing.JMenuItem miLentele;
    private javax.swing.JMenuItem miPavadinimas;
    private javax.swing.JMenuItem miRibos;
    private javax.swing.JMenuItem miUzdaryti;
    private javax.swing.JTextArea tekstoLaukas;
    private javax.swing.JTextField textIki;
    private javax.swing.JTextField textNuo;
    // End of variables declaration//GEN-END:variables
}
